version: '3.8'

services:
  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: ${MONGO_URL}
      PORT: ${PORT}
      MONGO_DB: ${MONGO_DB}

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    